"""Copy for the Kalma brand deck in Bahasa Indonesia (id), English (en) and Español (es)."""

COLOR_NAMES = {
    "id": {"sand": "Pasir Kalma", "lagoon": "Laguna", "deep": "Laut Dalam", "shell": "Kerang", "drift": "Kayu Hanyut",
           "lagoondeep": "Laguna Dalam", "ink": "Tinta Malam", "coral": "Karang", "coraldeep": "Karang Tua", "jungle": "Hutan"},
    "en": {"sand": "Kalma Sand", "lagoon": "Lagoon", "deep": "Deep Sea", "shell": "Seashell", "drift": "Driftwood",
           "lagoondeep": "Deep Lagoon", "ink": "Night Ink", "coral": "Coral", "coraldeep": "Burnt Coral", "jungle": "Jungle"},
    "es": {"sand": "Arena Kalma", "lagoon": "Laguna", "deep": "Mar Profundo", "shell": "Concha", "drift": "Madera de Deriva",
           "lagoondeep": "Laguna Profunda", "ink": "Tinta Nocturna", "coral": "Coral", "coraldeep": "Coral Tostado", "jungle": "Selva"},
}

TEXT = {
# =====================================================================  INDONESIA
"id": {
  "lang": "id", "doc_title": "Kalma Raja Ampat — Brand Guidelines (ID)",
  "foot": "Brand Identity Guidelines", "credit": "Dikerjakan oleh",
  "ch": ["Esensi Brand", "Logo", "Warna", "Tipografi", "Elemen Grafis", "Fotografi", "Tone of Voice", "Komponen Website", "Aplikasi", "Aset"],
  "s": {
    "cover": {"kick": "Brand Identity Guidelines · v1.0", "title": "Tenang seperti laguna, hangat seperti pasir.",
              "for": "Disiapkan untuk", "by": "Disiapkan oleh", "date": "Oktober 2026 · Dokumen presentasi klien"},
    "toc": {"kick": "Daftar isi", "title": "Isi dokumen",
            "note": "Harga, jumlah kamar, rating, dan detail fasilitas pada contoh adalah placeholder dan perlu diganti dengan data asli Kalma."},
    "ess": {
      "title": "Makna di balik nama", "k_name": "Makna nama",
      "quote": "“Kalma”, dari <em>calm</em>: ketenangan yang ditemukan saat waktu melambat di tengah laut Raja Ampat.",
      "p1": "Kalma adalah homestay di Raja Ampat, Papua Barat Daya: rumah kayu sederhana di tepi air jernih, dikelola dengan keramahan lokal. Kami tidak menjual kemewahan. Kami menawarkan <b>jeda</b>: bangun dengan suara ombak, snorkeling dari depan kamar, makan ikan bakar bersama keluarga tuan rumah.",
      "p2": "Gelombang yang membelah logo menjadi dua warna adalah garis permukaan air: atas adalah laguna yang terang, bawah adalah kedalaman laut yang tenang. Huruf-hurufnya meliuk seperti daun kelapa dan sirip ikan.",
      "title2": "Visi, misi & positioning",
      "vis_k": "Visi", "vis": "Menjadi rumah singgah paling menenangkan di Raja Ampat.",
      "vis_d": "Tempat tamu pulang dengan pikiran lebih ringan dan cerita tentang orang-orangnya, bukan hanya pemandangannya.",
      "mis_k": "Misi", "mis": ["Penginapan bersih, nyaman, dan jujur harganya.", "Membuka pengalaman laut & budaya Papua secara autentik.", "Menjaga karang dan memberdayakan warga kampung."],
      "pos_k": "Positioning", "pos": "Untuk pelancong yang ingin melambat.",
      "pos_d": "Berbeda dari resort mewah dan dive camp yang padat jadwal, Kalma menawarkan ketenangan, kehangatan keluarga lokal, dan akses langsung ke terumbu.",
      "title3": "Nilai, kepribadian & tagline", "val_k": "Nilai inti",
      "values": [("Tenang", "Tidak terburu-buru, ruang untuk bernapas."), ("Hangat", "Tamu disambut seperti keluarga."),
                 ("Jujur", "Apa adanya, tanpa janji berlebihan."), ("Menjaga", "Laut, karang, dan kampung tetap lestari.")],
      "per_k": "Kepribadian brand", "pers": ["Kalem", "Ramah", "Membumi", "Ceria secukupnya", "Tulus", "Peduli alam"],
      "tag": "Slow down, Raja Ampat style.", "tag_alt": "Alternatif: “Pelan-pelan saja di Raja Ampat.” · “Where the reef meets home.”"},
    "logo": {
      "title": "Anatomi logo", "lead": "Wordmark tulisan tangan dengan garis gelombang dua warna. Logo adalah aset paling berharga: jangan digambar ulang, selalu pakai file resmi.",
      "wave": "Garis gelombang",
      "a1": "Huruf organik yang meliuk seperti daun dan sirip. Bentuknya unik dan tidak boleh diganti font lain.",
      "a2": "Membagi huruf menjadi Laguna (atas) dan Laut Dalam (bawah). Ini ciri khas Kalma dan sumber semua elemen grafis gelombang.",
      "a3": "Kapital dengan spasi huruf lebar untuk menegaskan lokasi. Boleh dilepas hanya pada versi wordmark.",
      "vector": "Catatan: file logo saat ini berupa PNG resolusi tinggi. Untuk cetak besar (spanduk, papan nama) gunakan versi vektor (SVG/AI/PDF).",
      "var_title": "Varian logo", "var_lead": "Pilih varian sesuai latar dan ruang. Prioritas: Utama → Putih → Monokrom → Wordmark → Monogram.",
      "variants": [("A. Utama (full color)", "Default, di atas Pasir, Kerang, atau putih."), ("B. Putih (reversed)", "Di atas Laut Dalam, Tinta Malam, atau foto gelap."),
                   ("C. Monokrom Laut Dalam", "Cetak 1 warna, stempel, sablon, faktur."), ("D. Wordmark", "Tanpa descriptor: header website & ruang sempit."),
                   ("E. Monogram “K”", "Favicon, foto profil sosmed, ikon aplikasi, watermark."), ("F. Monokrom Pasir", "Di atas Laguna/Laut Dalam untuk merchandise.")],
      "cs_title": "Area aman & ukuran minimum",
      "cs_d": "Sisakan ruang kosong minimal <b>X</b> (tinggi huruf “a” pada wordmark, ±25% tinggi logo) di semua sisi.",
      "min_t": "Ukuran minimum", "min_d": "Di bawah ukuran ini descriptor tidak terbaca; gunakan wordmark atau monogram.", "min1": "Logo utama", "min3": "Monogram",
      "place_t": "Penempatan", "place": ["Website: wordmark di kiri atas header, tinggi 32–40 px.", "Cetak: pojok kiri atas atau tengah, jauh dari lipatan.", "Sosmed: monogram untuk foto profil, logo kecil sebagai watermark."],
      "bg_title": "Logo di atas berbagai latar", "bg_lead": "Pastikan kontras selalu cukup. Latar Pasir adalah pilihan paling ideal.",
      "bgs": ["Pasir: paling ideal", "Putih / Kerang", "Laut Dalam + logo putih", "Foto tenang/gelap + logo putih"],
      "mis_title": "Larangan penggunaan logo",
      "misuse": ["Jangan meregangkan / memipihkan", "Jangan memutar", "Jangan mengganti warna di luar palet", "Jangan diberi bayangan atau efek 3D",
                 "Jangan logo berwarna di atas biru", "Jangan di atas latar ramai", "Jangan dibuat transparan/pudar", "Jangan mengetik ulang dengan font lain"]},
    "col": {
      "names": COLOR_NAMES["id"],
      "uses": {"sand": "Latar utama brand: website, kartu nama, kemasan.", "lagoon": "Grafis, ilustrasi, ikon, garis gelombang.",
               "deep": "Judul, tombol utama, section gelap, footer.", "shell": "Permukaan kartu, section selang-seling.",
               "drift": "Border, garis pemisah, ilustrasi.", "lagoondeep": "Link & teks biru (lolos AA).", "ink": "Teks body, pengganti hitam.",
               "coral": "CTA pemesanan & highlight promo.", "coraldeep": "Teks aksen / harga di latar terang.", "jungle": "Label eco, aktivitas alam."},
      "core_t": "Warna inti", "core_l": "Tiga warna ini diambil langsung dari logo dan menjadi identitas utama Kalma.",
      "sup_t": "Warna pendukung & aksen", "sup_l": "Melengkapi warna inti untuk teks, permukaan, dan ajakan bertindak (CTA).",
      "prop_t": "Proporsi & aksesibilitas", "prop_h": "Proporsi penggunaan",
      "prop_d": "Pasir dominan agar kesan hangat dan lapang. Biru menjadi “suara” brand. Karang hanya untuk hal yang harus diklik.",
      "cmyk_note": "Nilai CMYK adalah perkiraan; selalu minta proof cetak, terutama untuk warna Pasir.",
      "acc_h": "Kombinasi teks yang aman dibaca", "deco": "2.9 : 1 · hanya judul besar",
      "pairnames": ["Laut Dalam", "Tinta Malam", "Putih", "Laguna Dalam", "Tinta Malam", "Laguna"],
      "tint_t": "Skala tint & shade", "tint_l": "Turunan terang–gelap dari setiap warna untuk latar, hover, ilustrasi, dan grafik. Kotak bergaris tepi adalah warna aslinya (500).",
      "pal_t": "Pilihan arah warna", "rec": "REKOMENDASI", "best": "Cocok untuk:",
      "pal_l": "Alternatif palet yang tetap serasi dengan logo. Klien dapat memilih satu arah sebagai warna utama website & materi promosi.",
      "pal_l2": "Semua palet memakai logo yang sama; hanya warna latar, aksen, dan tombol yang berubah.",
      "prev_t": "Bangun dengan suara ombak.", "prev_b": "Pesan kamar",
      "pal": {"A": ("Laguna Klasik", "Seimbang antara pasir hangat dan biru laut, setia pada warna logo.", "website utama, semua materi."),
              "B": ("Senja di Dermaga", "Jingga senja dan emas memberi kesan romantis dan hangat.", "promo honeymoon, musim liburan."),
              "C": ("Hutan & Karang", "Hijau hutan karst memberi nuansa eco dan petualangan.", "paket trekking, birdwatching, eco-tour."),
              "D": ("Toska Tropis", "Toska cerah dan kuning matahari, segar dan ceria.", "media sosial, paket snorkeling keluarga."),
              "E": ("Malam Tenang", "Gelap, elegan, dan premium dengan aksen pasir.", "materi premium, undangan, menu malam."),
              "F": ("Pasir Putih Minimal", "Putih bersih dan lapang, foto menjadi pusat perhatian.", "website galeri foto, katalog kamar.")}},
    "type": {
      "title": "Tipografi", "lead": "Dua keluarga huruf gratis dari Google Fonts: serif lembut untuk kehangatan, sans buatan Indonesia untuk keterbacaan.",
      "disp_k": "Display · Judul", "disp_d": "Serif dengan sudut membulat (sumbu SOFT 100), senada dengan lekuk logo. Untuk judul, kutipan, dan angka harga. Bobot 300–500; italic untuk kutipan.",
      "body_k": "Teks · UI", "body_d": "Sans geometris karya desainer Indonesia (Tokotype). Untuk body, navigasi, tombol, form, dan label kapital ber-spasi lebar. Bobot 400–700.",
      "h_title": "Hierarki & aturan pakai",
      "h": ["Homestay di Raja Ampat", "Bangun dengan suara ombak.", "Kamar di atas air", "Paket snorkeling 3 hari",
            "Sarapan, makan siang, dan makan malam sudah termasuk, mengikuti tangkapan nelayan kampung.", "Foto: dermaga Kalma, pukul 06.10 WIT."],
      "do_t": "Lakukan", "do": ["Judul memakai sentence case.", "Panjang baris body 55–75 karakter.", "Harga & angka besar memakai Fraunces."],
      "dont_t": "Hindari", "dont": ["Font script lain yang bersaing dengan logo.", "Paragraf panjang huruf kapital semua.", "Lebih dari 2 keluarga font."]},
    "gfx": {
      "title": "Elemen grafis", "lead": "Semua elemen grafis diturunkan dari garis gelombang logo: lembut, mengalir, tanpa sudut tajam.",
      "g1": ("Pemisah gelombang", "Transisi antar-section website & bagian bawah poster."), "g2": ("Pola riak", "Latar halus kemasan & kertas surat, opasitas 15–35%."),
      "g3": ("Pola riak gelap", "Footer, kartu nama belakang, merchandise."),
      "shape_t": "Bentuk organik", "shape_d": "Bingkai foto berbentuk lengkung (arch) atau blob seperti batu karang. Radius besar, tanpa sudut tajam.",
      "icon_t": "Ikon", "icon_d": "Garis 1.75 px, ujung membulat, warna Laut Dalam di atas kotak Pasir. Rekomendasi set: Lucide atau Phosphor.",
      "icons": ["Snorkeling", "Kamar", "Boat trip", "Makan", "Sunrise", "Eco"]},
    "photo": {
      "title": "Fotografi", "lead": "Cahaya alami, tenang, jujur, dan selalu ada rasa “manusia”. Kotak di bawah adalah ilustrasi suasana warna.",
      "tiles": ["Golden hour di dermaga", "Laguna & pulau karst", "Detail kamar kayu", "Bawah air: karang & ikan"],
      "do_t": "Cari momen seperti ini", "do": ["Pagi & sore hari, cahaya lembut.", "Komposisi lapang, ada ruang untuk teks.", "Orang sungguhan: tuan rumah, nelayan, tamu (dengan izin).", "Warna natural, sedikit hangat."],
      "dont_t": "Hindari", "dont": ["Saturasi berlebihan atau HDR “neon”.", "Foto stok yang bukan Raja Ampat.", "Sampah atau aktivitas yang merusak karang.", "Watermark besar di tengah foto."]},
    "voice": {
      "title": "Tone of voice", "lead": "Kalma berbicara seperti tuan rumah yang ramah menjemput tamu di dermaga: santai, hangat, tidak berlebihan.",
      "principles": [("Tenang, bukan malas", "Kalimat pendek, ritme pelan, tanpa tanda seru beruntun."), ("Hangat, bukan lebay", "Sapa dengan “kamu”, hindari superlatif kosong."),
                     ("Jujur & jelas", "Sebut apa adanya: listrik, sinyal, waktu tempuh."), ("Lokal & peduli", "Sisipkan kata lokal dan pesan menjaga laut.")],
      "th": ["Situasi", "Gaya Kalma", "Bukan Kalma"],
      "rows": [("Hero website", "Bangun dengan suara ombak. Sisanya, biar laut yang atur.", "RESORT TERBAIK DAN TERMURAH DI RAJA AMPAT!!!"),
               ("Tombol", "Cek ketersediaan · Pesan kamar · Tanya via WhatsApp", "Klik di sini · Submit · BURUAN PESAN"),
               ("Info praktis", "Listrik menyala 18.00–06.00. Sinyal ada di dermaga.", "Fasilitas lengkap 24 jam."),
               ("Caption IG", "Pagi ini lautnya diam sekali. Kopi, dermaga, dan tidak ada rencana.", "Guys wajib banget ke sini, auto healing parah!!!")]},
    "ui": {
      "title": "Komponen website", "lead": "Dasar UI website. Semua nilai tersedia di file tokens.css agar developer konsisten.",
      "btn_t": "Tombol", "b": ["Pesan kamar", "Cek ketersediaan", "Lihat paket", "Tanya via WhatsApp"],
      "btn_d": "Karang hanya untuk 1 aksi utama per layar. Bentuk pill, tinggi minimal 48 px, label kata kerja maks. 3 kata.",
      "badges": ["Snorkeling", "Eco-friendly", "Sisa 2 kamar", "Termasuk makan 3x"], "guests": "Jumlah tamu", "guests_v": "2 dewasa",
      "room_b": "Di atas air", "room": "Bungalow Laguna", "room_d": "Kasur double, kelambu, teras pribadi dengan tangga ke laut.", "per": "/ malam", "detail": "Detail"},
    "app": {
      "web_t": "Aplikasi: website", "nav": ["Kamar", "Pengalaman", "Cerita", "Lokasi"], "book": "Pesan",
      "hero": "Bangun dengan suara ombak.", "hero_d": "Rumah kayu di tepi laguna, makan bersama keluarga lokal, dan karang tepat di depan kamar.",
      "cta1": "Cek ketersediaan", "cta2": "Lihat kamar", "stats": [("4.9 ★", "ulasan tamu"), ("5 kamar", "di atas air"), ("10 menit", "ke spot manta")],
      "note": "Angka di atas adalah contoh (placeholder).",
      "print_t": "Aplikasi: cetak & media sosial", "owner": "Nama Pemilik", "biz": ("Kartu nama", "85 × 55 mm. Depan Pasir, belakang Laut Dalam."),
      "igq": "“Di sini, jam tidak terlalu penting.”", "ig1": ("Paket", "3H2M Snorkel"), "ig2": ("Bawah laut", "Kebun karang"),
      "igc": ("Feed Instagram", "Selang-seling kutipan, foto berlabel, dan monogram."), "welcome": "Selamat datang · Welcome",
      "sign": ("Papan nama & gantungan kunci", "Nama kamar memakai nama alam lokal.")},
    "assets": {
      "title": "File & aset", "lead": "Semua file diserahkan dalam folder brand/assets. Latar transparan kecuali file original.",
      "desc": ["Logo utama, transparan", "Logo putih", "Monokrom Laut Dalam", "Monokrom Pasir", "Wordmark tanpa descriptor", "Wordmark putih",
               "Monogram “K”", "Ikon 512 px untuk sosmed", "Ikon website"], "tokens": "Design tokens untuk developer"},
    "close": {"title": "Terima kasih", "lead": "Kami siap melanjutkan ke tahap desain dan pengembangan website Kalma Raja Ampat."}}},

# =====================================================================  ENGLISH
"en": {
  "lang": "en", "doc_title": "Kalma Raja Ampat — Brand Guidelines (EN)",
  "foot": "Brand Identity Guidelines", "credit": "Crafted by",
  "ch": ["Brand Essence", "Logo", "Color", "Typography", "Graphic Elements", "Photography", "Tone of Voice", "Website Components", "Applications", "Assets"],
  "s": {
    "cover": {"kick": "Brand Identity Guidelines · v1.0", "title": "Calm as the lagoon, warm as the sand.",
              "for": "Prepared for", "by": "Prepared by", "date": "October 2026 · Client presentation"},
    "toc": {"kick": "Contents", "title": "What's inside",
            "note": "Prices, room counts, ratings and facility details shown in examples are placeholders to be replaced with Kalma's real data."},
    "ess": {
      "title": "The meaning behind the name", "k_name": "The name",
      "quote": "“Kalma”, from <em>calm</em>: the stillness you find when time slows down in the middle of Raja Ampat's sea.",
      "p1": "Kalma is a homestay in Raja Ampat, Southwest Papua: a simple wooden house by crystal-clear water, run with local hospitality. We don't sell luxury. We offer a <b>pause</b>: waking up to the sound of waves, snorkeling right off your room, sharing grilled fish with your host family.",
      "p2": "The wave that splits the logo into two colors is the waterline: above is the bright lagoon, below is the calm depth of the sea. The letters curve like palm fronds and fish fins.",
      "title2": "Vision, mission & positioning",
      "vis_k": "Vision", "vis": "To be the most peaceful place to stay in Raja Ampat.",
      "vis_d": "A place guests leave with a lighter mind and stories about the people, not just the views.",
      "mis_k": "Mission", "mis": ["Clean, comfortable, honestly priced stays.", "Open up authentic sea & Papuan cultural experiences.", "Protect the reef and empower the village."],
      "pos_k": "Positioning", "pos": "For travelers who want to slow down.",
      "pos_d": "Unlike luxury resorts and busy dive camps, Kalma offers calm, the warmth of a local family, and direct access to the reef.",
      "title3": "Values, personality & tagline", "val_k": "Core values",
      "values": [("Calm", "Never in a rush; room to breathe."), ("Warm", "Guests are welcomed like family."),
                 ("Honest", "As it is, no over-promising."), ("Caring", "Keeping the sea, reef and village thriving.")],
      "per_k": "Brand personality", "pers": ["Easygoing", "Friendly", "Grounded", "Gently cheerful", "Sincere", "Nature-minded"],
      "tag": "Slow down, Raja Ampat style.", "tag_alt": "Alternatives: “Where the reef meets home.” · “Pelan-pelan saja.”"},
    "logo": {
      "title": "Logo anatomy", "lead": "A hand-lettered wordmark split by a two-tone wave. The logo is our most valuable asset: never redraw it, always use the official files.",
      "wave": "Wave line",
      "a1": "Organic letters that curve like leaves and fins. The shapes are unique and must never be replaced by another font.",
      "a2": "Splits the letters into Lagoon (top) and Deep Sea (bottom). It is Kalma's signature and the source of every wave graphic.",
      "a3": "Widely tracked capitals that anchor the location. May be removed only in the wordmark version.",
      "vector": "Note: the logo is currently a high-resolution PNG. For large print (banners, signage) use a vector version (SVG/AI/PDF).",
      "var_title": "Logo variants", "var_lead": "Choose the variant by background and space. Priority: Primary → White → Mono → Wordmark → Monogram.",
      "variants": [("A. Primary (full color)", "Default, on Sand, Seashell or white."), ("B. White (reversed)", "On Deep Sea, Night Ink or dark photos."),
                   ("C. Deep Sea mono", "One-color print, stamps, screen print, invoices."), ("D. Wordmark", "No descriptor: website header & tight spaces."),
                   ("E. “K” monogram", "Favicon, social avatar, app icon, watermark."), ("F. Sand mono", "On Lagoon/Deep Sea for merchandise.")],
      "cs_title": "Clear space & minimum size",
      "cs_d": "Keep a minimum clear space of <b>X</b> (the height of the “a” in the wordmark, about 25% of the logo height) on all sides.",
      "min_t": "Minimum size", "min_d": "Below these sizes the descriptor becomes illegible; use the wordmark or monogram.", "min1": "Primary logo", "min3": "Monogram",
      "place_t": "Placement", "place": ["Website: wordmark top-left in the header, 32–40 px tall.", "Print: top-left or centered, away from folds.", "Social: monogram as avatar, small logo as a watermark."],
      "bg_title": "Logo on backgrounds", "bg_lead": "Always ensure enough contrast. Sand is the ideal background.",
      "bgs": ["Sand: ideal", "White / Seashell", "Deep Sea + white logo", "Calm/dark photo + white logo"],
      "mis_title": "Logo misuse",
      "misuse": ["Don't stretch or squash", "Don't rotate", "Don't recolor outside the palette", "Don't add shadows or 3D effects",
                 "Don't place the color logo on blue", "Don't use busy backgrounds", "Don't fade or make transparent", "Don't retype it in another font"]},
    "col": {
      "names": COLOR_NAMES["en"],
      "uses": {"sand": "Main brand background: website, business cards, packaging.", "lagoon": "Graphics, illustration, icons, wave lines.",
               "deep": "Headings, primary buttons, dark sections, footer.", "shell": "Card surfaces, alternating sections.",
               "drift": "Borders, dividers, illustration.", "lagoondeep": "Links & blue text (AA compliant).", "ink": "Body text, replaces black.",
               "coral": "Booking CTA & promo highlights.", "coraldeep": "Accent text / prices on light backgrounds.", "jungle": "Eco labels, nature activities."},
      "core_t": "Core colors", "core_l": "These three colors come straight from the logo and form Kalma's primary identity.",
      "sup_t": "Supporting & accent colors", "sup_l": "They complement the core colors for text, surfaces and calls to action.",
      "prop_t": "Proportion & accessibility", "prop_h": "Color proportion",
      "prop_d": "Sand dominates for a warm, open feel. Blue is the brand's “voice”. Coral is only for what must be clicked.",
      "cmyk_note": "CMYK values are approximate; always request a print proof, especially for Sand.",
      "acc_h": "Readable text pairings", "deco": "2.9 : 1 · large headings only",
      "pairnames": ["Deep Sea", "Night Ink", "White", "Deep Lagoon", "Night Ink", "Lagoon"],
      "tint_t": "Tints & shades", "tint_l": "Light-to-dark steps of each color for backgrounds, hover states, illustration and charts. The outlined swatch is the original (500).",
      "pal_t": "Color directions", "rec": "RECOMMENDED", "best": "Best for:",
      "pal_l": "Alternative palettes that stay in harmony with the logo. The client can pick one direction as the main color for the website and promotional material.",
      "pal_l2": "Every palette uses the same logo; only backgrounds, accents and buttons change.",
      "prev_t": "Wake up to the sound of waves.", "prev_b": "Book a room",
      "pal": {"A": ("Classic Lagoon", "A balance of warm sand and sea blue, true to the logo.", "the main website and all materials."),
              "B": ("Sunset Pier", "Sunset orange and gold feel romantic and warm.", "honeymoon offers, holiday season."),
              "C": ("Jungle & Reef", "Karst-forest green gives an eco, adventurous mood.", "trekking, birdwatching, eco-tours."),
              "D": ("Tropical Turquoise", "Bright teal and sunny yellow, fresh and playful.", "social media, family snorkel packages."),
              "E": ("Quiet Night", "Dark, elegant and premium with sand accents.", "premium material, invitations, dinner menus."),
              "F": ("White Sand Minimal", "Clean, airy white that lets photos lead.", "photo-gallery website, room catalogue.")}},
    "type": {
      "title": "Typography", "lead": "Two free Google Fonts families: a soft serif for warmth and an Indonesian-made sans for readability.",
      "disp_k": "Display · Headings", "disp_d": "A serif with rounded corners (SOFT axis 100) that echoes the logo's curves. For headings, quotes and prices. Weights 300–500; italic for quotes.",
      "body_k": "Text · UI", "body_d": "A geometric sans by Indonesian foundry Tokotype. For body copy, navigation, buttons, forms and widely tracked caps labels. Weights 400–700.",
      "h_title": "Hierarchy & usage",
      "h": ["Homestay in Raja Ampat", "Wake up to the sound of waves.", "Overwater rooms", "3-day snorkel package",
            "Breakfast, lunch and dinner are included, based on the village fishermen's daily catch.", "Photo: Kalma pier at 6:10 a.m."],
      "do_t": "Do", "do": ["Use sentence case for headings.", "Keep body lines at 55–75 characters.", "Set prices & large numbers in Fraunces."],
      "dont_t": "Avoid", "dont": ["Other script fonts that compete with the logo.", "Long paragraphs in all caps.", "More than 2 font families."]},
    "gfx": {
      "title": "Graphic elements", "lead": "Every graphic element derives from the logo's wave: soft, flowing, with no sharp corners.",
      "g1": ("Wave divider", "Section transitions on the website & poster footers."), "g2": ("Ripple pattern", "Subtle background for packaging & stationery, 15–35% opacity."),
      "g3": ("Dark ripple pattern", "Footer, business card backs, merchandise."),
      "shape_t": "Organic shapes", "shape_d": "Photo frames shaped like arches or coral-stone blobs. Large radii, no sharp corners.",
      "icon_t": "Icons", "icon_d": "1.75 px outline, rounded ends, Deep Sea on a Sand tile. Recommended sets: Lucide or Phosphor.",
      "icons": ["Snorkeling", "Rooms", "Boat trip", "Dining", "Sunrise", "Eco"]},
    "photo": {
      "title": "Photography", "lead": "Natural light, calm, honest, always with a human touch. The tiles below illustrate the color mood.",
      "tiles": ["Golden hour on the pier", "Lagoon & karst islands", "Wooden room details", "Underwater: coral & fish"],
      "do_t": "Look for moments like these", "do": ["Early morning & late afternoon, soft light.", "Open compositions with space for text.", "Real people: hosts, fishermen, guests (with consent).", "Natural, slightly warm color."],
      "dont_t": "Avoid", "dont": ["Oversaturation or “neon” HDR.", "Stock photos that aren't Raja Ampat.", "Litter or reef-damaging activities.", "Large watermarks in the middle."]},
    "voice": {
      "title": "Tone of voice", "lead": "Kalma speaks like a friendly host picking guests up at the pier: relaxed, warm, never over the top.",
      "principles": [("Calm, not lazy", "Short sentences, slow rhythm, no strings of exclamation marks."), ("Warm, not cheesy", "Speak to “you”; skip empty superlatives."),
                     ("Honest & clear", "Say it as it is: power, signal, travel time."), ("Local & caring", "Add local words and a reminder to protect the sea.")],
      "th": ["Situation", "Kalma style", "Not Kalma"],
      "rows": [("Website hero", "Wake up to the sound of waves. Let the sea plan the rest.", "BEST AND CHEAPEST RESORT IN RAJA AMPAT!!!"),
               ("Buttons", "Check availability · Book a room · Ask on WhatsApp", "Click here · Submit · BOOK NOW HURRY"),
               ("Practical info", "Power runs 6 p.m.–6 a.m. There's signal on the pier.", "Full facilities 24/7."),
               ("Instagram caption", "The sea is so still this morning. Coffee, the pier, and no plans.", "Guys you NEED to go here, ultimate healing!!!")]},
    "ui": {
      "title": "Website components", "lead": "UI foundations for the website. All values live in tokens.css so developers stay consistent.",
      "btn_t": "Buttons", "b": ["Book a room", "Check availability", "View packages", "Ask on WhatsApp"],
      "btn_d": "Coral is reserved for one primary action per screen. Pill shape, min. 48 px tall, verb labels of max. 3 words.",
      "badges": ["Snorkeling", "Eco-friendly", "2 rooms left", "3 meals included"], "guests": "Guests", "guests_v": "2 adults",
      "room_b": "Overwater", "room": "Lagoon Bungalow", "room_d": "Double bed, mosquito net, private terrace with steps into the sea.", "per": "/ night", "detail": "Details"},
    "app": {
      "web_t": "Applications: website", "nav": ["Rooms", "Experiences", "Stories", "Location"], "book": "Book",
      "hero": "Wake up to the sound of waves.", "hero_d": "A wooden house on the lagoon, meals with a local family, and coral right outside your room.",
      "cta1": "Check availability", "cta2": "See rooms", "stats": [("4.9 ★", "guest reviews"), ("5 rooms", "over the water"), ("10 min", "to the manta spot")],
      "note": "Figures shown are examples (placeholders).",
      "print_t": "Applications: print & social", "owner": "Owner Name", "biz": ("Business card", "85 × 55 mm. Sand front, Deep Sea back."),
      "igq": "“Here, clocks don't matter much.”", "ig1": ("Package", "3D2N Snorkel"), "ig2": ("Underwater", "Coral garden"),
      "igc": ("Instagram feed", "Alternate quotes, labeled photos and the monogram."), "welcome": "Selamat datang · Welcome",
      "sign": ("Signage & key tags", "Rooms are named after local nature.")},
    "assets": {
      "title": "Files & assets", "lead": "All files are delivered in the brand/assets folder. Transparent backgrounds except the original file.",
      "desc": ["Primary logo, transparent", "White logo", "Deep Sea mono", "Sand mono", "Wordmark without descriptor", "White wordmark",
               "“K” monogram", "512 px social icon", "Website icons"], "tokens": "Design tokens for developers"},
    "close": {"title": "Thank you", "lead": "We're ready to move on to designing and building the Kalma Raja Ampat website."}}},

# =====================================================================  ESPAÑOL
"es": {
  "lang": "es", "doc_title": "Kalma Raja Ampat — Manual de Marca (ES)",
  "foot": "Manual de Identidad de Marca", "credit": "Elaborado por",
  "ch": ["Esencia de Marca", "Logotipo", "Color", "Tipografía", "Elementos Gráficos", "Fotografía", "Tono de Voz", "Componentes Web", "Aplicaciones", "Recursos"],
  "s": {
    "cover": {"kick": "Manual de Identidad de Marca · v1.0", "title": "Sereno como la laguna, cálido como la arena.",
              "for": "Preparado para", "by": "Preparado por", "date": "Octubre 2026 · Presentación para el cliente"},
    "toc": {"kick": "Contenido", "title": "Índice",
            "note": "Los precios, número de habitaciones, valoraciones y detalles de servicios en los ejemplos son provisionales y deben sustituirse por los datos reales de Kalma."},
    "ess": {
      "title": "El significado del nombre", "k_name": "El nombre",
      "quote": "“Kalma”, de <em>calm</em> (calma): la serenidad que aparece cuando el tiempo se detiene en medio del mar de Raja Ampat.",
      "p1": "Kalma es un homestay en Raja Ampat, Papúa Suroccidental: una sencilla casa de madera junto a aguas cristalinas, gestionada con hospitalidad local. No vendemos lujo. Ofrecemos una <b>pausa</b>: despertar con el sonido de las olas, hacer snorkel frente a la habitación y compartir pescado a la brasa con la familia anfitriona.",
      "p2": "La ola que divide el logotipo en dos colores es la línea del agua: arriba, la laguna luminosa; abajo, la calma del mar profundo. Las letras se curvan como hojas de palma y aletas de pez.",
      "title2": "Visión, misión y posicionamiento",
      "vis_k": "Visión", "vis": "Ser el alojamiento más sereno de Raja Ampat.",
      "vis_d": "Un lugar del que los huéspedes se van con la mente más ligera e historias sobre su gente, no solo sobre el paisaje.",
      "mis_k": "Misión", "mis": ["Alojamiento limpio, cómodo y a precio honesto.", "Abrir experiencias auténticas de mar y cultura papú.", "Proteger el arrecife y apoyar a la comunidad local."],
      "pos_k": "Posicionamiento", "pos": "Para viajeros que quieren ir más despacio.",
      "pos_d": "A diferencia de los resorts de lujo y los campamentos de buceo con agendas llenas, Kalma ofrece calma, el calor de una familia local y acceso directo al arrecife.",
      "title3": "Valores, personalidad y eslogan", "val_k": "Valores",
      "values": [("Calma", "Sin prisas; espacio para respirar."), ("Calidez", "Recibimos al huésped como a la familia."),
                 ("Honestidad", "Tal como es, sin promesas exageradas."), ("Cuidado", "Mantener vivos el mar, el arrecife y la aldea.")],
      "per_k": "Personalidad de marca", "pers": ["Tranquila", "Amable", "Auténtica", "Alegre con medida", "Sincera", "Consciente de la naturaleza"],
      "tag": "Slow down, Raja Ampat style.", "tag_alt": "Versión en español: “Sin prisa, al estilo Raja Ampat.” · “Donde el arrecife es hogar.”"},
    "logo": {
      "title": "Anatomía del logotipo", "lead": "Un logotipo caligráfico dividido por una ola bicolor. Es nuestro activo más valioso: nunca lo redibujes, usa siempre los archivos oficiales.",
      "wave": "Línea de ola",
      "a1": "Letras orgánicas que se curvan como hojas y aletas. Sus formas son únicas y no deben sustituirse por otra fuente.",
      "a2": "Divide las letras en Laguna (arriba) y Mar Profundo (abajo). Es la firma de Kalma y el origen de todos los gráficos de ola.",
      "a3": "Mayúsculas con amplio espaciado que anclan la ubicación. Solo puede omitirse en la versión wordmark.",
      "vector": "Nota: el logotipo es actualmente un PNG de alta resolución. Para impresión grande (pancartas, señalética) usa una versión vectorial (SVG/AI/PDF).",
      "var_title": "Variantes del logotipo", "var_lead": "Elige la variante según el fondo y el espacio. Prioridad: Principal → Blanco → Monocromo → Wordmark → Monograma.",
      "variants": [("A. Principal (a color)", "Por defecto, sobre Arena, Concha o blanco."), ("B. Blanco (invertido)", "Sobre Mar Profundo, Tinta Nocturna o fotos oscuras."),
                   ("C. Monocromo Mar Profundo", "Impresión a una tinta, sellos, serigrafía, facturas."), ("D. Wordmark", "Sin descriptor: cabecera web y espacios reducidos."),
                   ("E. Monograma “K”", "Favicon, avatar en redes, icono de app, marca de agua."), ("F. Monocromo Arena", "Sobre Laguna/Mar Profundo para merchandising.")],
      "cs_title": "Área de respeto y tamaño mínimo",
      "cs_d": "Deja un espacio libre mínimo de <b>X</b> (la altura de la “a” del wordmark, aprox. 25% de la altura del logo) en todos los lados.",
      "min_t": "Tamaño mínimo", "min_d": "Por debajo de estos tamaños el descriptor no se lee; usa el wordmark o el monograma.", "min1": "Logo principal", "min3": "Monograma",
      "place_t": "Ubicación", "place": ["Web: wordmark arriba a la izquierda en la cabecera, 32–40 px de alto.", "Impresión: arriba a la izquierda o centrado, lejos de pliegues.", "Redes: monograma como avatar, logo pequeño como marca de agua."],
      "bg_title": "Logotipo sobre fondos", "bg_lead": "Asegura siempre un contraste suficiente. Arena es el fondo ideal.",
      "bgs": ["Arena: ideal", "Blanco / Concha", "Mar Profundo + logo blanco", "Foto serena/oscura + logo blanco"],
      "mis_title": "Usos incorrectos del logotipo",
      "misuse": ["No estirar ni aplastar", "No rotar", "No cambiar colores fuera de la paleta", "No añadir sombras ni efectos 3D",
                 "No usar el logo a color sobre azul", "No usar fondos recargados", "No hacerlo transparente o tenue", "No reescribirlo con otra fuente"]},
    "col": {
      "names": COLOR_NAMES["es"],
      "uses": {"sand": "Fondo principal: web, tarjetas de visita, empaques.", "lagoon": "Gráficos, ilustración, iconos, líneas de ola.",
               "deep": "Títulos, botones principales, secciones oscuras, pie.", "shell": "Superficie de tarjetas, secciones alternas.",
               "drift": "Bordes, separadores, ilustración.", "lagoondeep": "Enlaces y texto azul (cumple AA).", "ink": "Texto de cuerpo, sustituye al negro.",
               "coral": "CTA de reserva y promociones.", "coraldeep": "Texto de acento / precios sobre fondos claros.", "jungle": "Etiquetas eco, actividades de naturaleza."},
      "core_t": "Colores principales", "core_l": "Estos tres colores provienen directamente del logotipo y forman la identidad principal de Kalma.",
      "sup_t": "Colores de apoyo y acento", "sup_l": "Complementan a los principales en textos, superficies y llamadas a la acción.",
      "prop_t": "Proporción y accesibilidad", "prop_h": "Proporción de uso",
      "prop_d": "La Arena domina para una sensación cálida y amplia. El azul es la “voz” de la marca. El Coral, solo para lo que debe pulsarse.",
      "cmyk_note": "Los valores CMYK son aproximados; solicita siempre una prueba de impresión, sobre todo para la Arena.",
      "acc_h": "Combinaciones de texto legibles", "deco": "2.9 : 1 · solo títulos grandes",
      "pairnames": ["Mar Profundo", "Tinta Nocturna", "Blanco", "Laguna Profunda", "Tinta Nocturna", "Laguna"],
      "tint_t": "Escala de tintes y sombras", "tint_l": "Variaciones de claro a oscuro de cada color para fondos, estados hover, ilustración y gráficos. La muestra con borde es el color original (500).",
      "pal_t": "Direcciones de color", "rec": "RECOMENDADA", "best": "Ideal para:",
      "pal_l": "Paletas alternativas en armonía con el logotipo. El cliente puede elegir una dirección como color principal de la web y del material promocional.",
      "pal_l2": "Todas las paletas usan el mismo logotipo; solo cambian fondos, acentos y botones.",
      "prev_t": "Despierta con el sonido de las olas.", "prev_b": "Reservar",
      "pal": {"A": ("Laguna Clásica", "Equilibrio entre arena cálida y azul mar, fiel al logotipo.", "la web principal y todo el material."),
              "B": ("Atardecer en el Muelle", "Naranja de atardecer y dorado: romántico y cálido.", "ofertas de luna de miel, temporada alta."),
              "C": ("Selva y Arrecife", "El verde de la selva kárstica aporta un aire eco y aventurero.", "trekking, observación de aves, ecotours."),
              "D": ("Turquesa Tropical", "Turquesa vivo y amarillo sol, fresco y alegre.", "redes sociales, paquetes de snorkel en familia."),
              "E": ("Noche Serena", "Oscura, elegante y premium con acentos arena.", "material premium, invitaciones, menús de cena."),
              "F": ("Arena Blanca Minimal", "Blanco limpio y amplio; las fotos son las protagonistas.", "web tipo galería, catálogo de habitaciones.")}},
    "type": {
      "title": "Tipografía", "lead": "Dos familias gratuitas de Google Fonts: una serif suave para la calidez y una sans indonesia para la legibilidad.",
      "disp_k": "Display · Títulos", "disp_d": "Serif de esquinas redondeadas (eje SOFT 100) que recuerda las curvas del logo. Para títulos, citas y precios. Pesos 300–500; cursiva para citas.",
      "body_k": "Texto · UI", "body_d": "Sans geométrica de la fundición indonesia Tokotype. Para texto, navegación, botones, formularios y etiquetas en mayúsculas espaciadas. Pesos 400–700.",
      "h_title": "Jerarquía y uso",
      "h": ["Homestay en Raja Ampat", "Despierta con el sonido de las olas.", "Habitaciones sobre el agua", "Paquete de snorkel de 3 días",
            "Desayuno, almuerzo y cena incluidos, según la pesca diaria de los pescadores locales.", "Foto: muelle de Kalma a las 6:10."],
      "do_t": "Haz", "do": ["Títulos en minúscula tipo oración.", "Líneas de texto de 55–75 caracteres.", "Precios y cifras grandes en Fraunces."],
      "dont_t": "Evita", "dont": ["Otras fuentes caligráficas que compitan con el logo.", "Párrafos largos en mayúsculas.", "Más de 2 familias tipográficas."]},
    "gfx": {
      "title": "Elementos gráficos", "lead": "Todos los elementos gráficos derivan de la ola del logotipo: suaves, fluidos, sin esquinas duras.",
      "g1": ("Separador de ola", "Transiciones entre secciones web y pie de carteles."), "g2": ("Patrón de ondas", "Fondo sutil para empaques y papelería, opacidad 15–35%."),
      "g3": ("Patrón de ondas oscuro", "Pie de página, reverso de tarjetas, merchandising."),
      "shape_t": "Formas orgánicas", "shape_d": "Marcos de foto en forma de arco o de piedra coralina. Radios amplios, sin esquinas duras.",
      "icon_t": "Iconos", "icon_d": "Trazo de 1.75 px, extremos redondeados, Mar Profundo sobre fondo Arena. Sets recomendados: Lucide o Phosphor.",
      "icons": ["Snorkel", "Habitación", "Paseo en barco", "Comida", "Amanecer", "Eco"]},
    "photo": {
      "title": "Fotografía", "lead": "Luz natural, serena, honesta y siempre con presencia humana. Los recuadros ilustran la atmósfera de color.",
      "tiles": ["Hora dorada en el muelle", "Laguna e islas kársticas", "Detalles de madera", "Bajo el agua: coral y peces"],
      "do_t": "Busca momentos así", "do": ["Primeras y últimas horas del día, luz suave.", "Composiciones amplias con espacio para texto.", "Personas reales: anfitriones, pescadores, huéspedes (con permiso).", "Color natural, ligeramente cálido."],
      "dont_t": "Evita", "dont": ["Saturación excesiva o HDR “neón”.", "Fotos de stock que no sean de Raja Ampat.", "Basura o actividades que dañen el arrecife.", "Marcas de agua grandes en el centro."]},
    "voice": {
      "title": "Tono de voz", "lead": "Kalma habla como un anfitrión amable que recibe a sus huéspedes en el muelle: relajado, cálido, nunca exagerado.",
      "principles": [("Calma, no pereza", "Frases cortas, ritmo pausado, sin cadenas de exclamaciones."), ("Cálido, no empalagoso", "Habla de tú; evita superlativos vacíos."),
                     ("Honesto y claro", "Dilo tal cual: electricidad, señal, tiempo de viaje."), ("Local y consciente", "Incluye palabras locales y el cuidado del mar.")],
      "th": ["Situación", "Estilo Kalma", "No es Kalma"],
      "rows": [("Portada web", "Despierta con el sonido de las olas. Deja que el mar planee el resto.", "¡¡¡EL MEJOR Y MÁS BARATO RESORT DE RAJA AMPAT!!!"),
               ("Botones", "Ver disponibilidad · Reservar · Escríbenos por WhatsApp", "Clic aquí · Enviar · RESERVA YA"),
               ("Información práctica", "Hay electricidad de 18:00 a 06:00. Hay señal en el muelle.", "Instalaciones completas 24 h."),
               ("Pie de foto en Instagram", "Esta mañana el mar está quieto. Café, muelle y ningún plan.", "¡¡Tienes que venir sí o sí, sanación total!!")]},
    "ui": {
      "title": "Componentes web", "lead": "Bases de interfaz para la web. Todos los valores están en tokens.css para que los desarrolladores sean coherentes.",
      "btn_t": "Botones", "b": ["Reservar", "Ver disponibilidad", "Ver paquetes", "Escríbenos por WhatsApp"],
      "btn_d": "El Coral se reserva para una sola acción principal por pantalla. Forma de píldora, mín. 48 px de alto, verbos de máx. 3 palabras.",
      "badges": ["Snorkel", "Eco-friendly", "Quedan 2 habitaciones", "3 comidas incluidas"], "guests": "Huéspedes", "guests_v": "2 adultos",
      "room_b": "Sobre el agua", "room": "Bungalow Laguna", "room_d": "Cama doble, mosquitera y terraza privada con escalera al mar.", "per": "/ noche", "detail": "Detalles"},
    "app": {
      "web_t": "Aplicaciones: sitio web", "nav": ["Habitaciones", "Experiencias", "Historias", "Ubicación"], "book": "Reservar",
      "hero": "Despierta con el sonido de las olas.", "hero_d": "Una casa de madera en la laguna, comidas con una familia local y coral frente a tu habitación.",
      "cta1": "Ver disponibilidad", "cta2": "Ver habitaciones", "stats": [("4.9 ★", "opiniones"), ("5 habitaciones", "sobre el agua"), ("10 min", "al punto de mantas")],
      "note": "Las cifras mostradas son ejemplos (provisionales).",
      "print_t": "Aplicaciones: impresos y redes", "owner": "Nombre del Propietario", "biz": ("Tarjeta de visita", "85 × 55 mm. Anverso Arena, reverso Mar Profundo."),
      "igq": "“Aquí, el reloj importa poco.”", "ig1": ("Paquete", "Snorkel 3D2N"), "ig2": ("Bajo el agua", "Jardín de coral"),
      "igc": ("Feed de Instagram", "Alterna citas, fotos con etiqueta y el monograma."), "welcome": "Selamat datang · Bienvenidos",
      "sign": ("Señalética y llaveros", "Las habitaciones llevan nombres de la naturaleza local.")},
    "assets": {
      "title": "Archivos y recursos", "lead": "Todos los archivos se entregan en la carpeta brand/assets. Fondo transparente salvo el archivo original.",
      "desc": ["Logo principal, transparente", "Logo blanco", "Monocromo Mar Profundo", "Monocromo Arena", "Wordmark sin descriptor", "Wordmark blanco",
               "Monograma “K”", "Icono de 512 px para redes", "Iconos web"], "tokens": "Design tokens para desarrolladores"},
    "close": {"title": "Gracias", "lead": "Estamos listos para pasar al diseño y desarrollo del sitio web de Kalma Raja Ampat."}}},
}
